user controller implementation
LuciusEg/collegePractice pull request #20
Opened 2022-12-20 16:23 UTC by Teilan

соединить

2022-12-21 10:13 UTC, LuciusEg commented
Неясно зачем добавлена папка Views с ее содержимым

2022-12-21 10:13 UTC, LuciusEg requested changes

2022-12-21 10:13 UTC, LuciusEg commented on documentation/documentation/Controllers/UsersController.cs
> +                return RedirectToAction(nameof(Index));
Не возвращает сообщения что все выполнилось успешно.

2022-12-22 07:42 UTC, LuciusEg requested changes

2022-12-22 07:42 UTC, LuciusEg commented on documentation/documentation/Controllers/UsersController.cs
> +        public async Task<ActionResult<IEnumerable<User>>> createUser(User userTO)
возвращаемый тип противоречит названию метода

2022-12-22 07:42 UTC, LuciusEg commented on documentation/documentation/Controllers/UsersController.cs
> +        public async Task<ActionResult<IEnumerable<User>>> UpdateUser(int id,  User userTO)
возвращаемый тип противоречит названию метода

2022-12-22 07:42 UTC, LuciusEg commented on documentation/documentation/Controllers/UsersController.cs
> +        public async Task<ActionResult<IEnumerable<User>>> DeleteUsers(int id)
"Удалить пользователей", хотя на входе тольо один id

2022-12-22 11:47 UTC, Teilan reviewed
попытка2

2022-12-22 11:58 UTC, Teilan commented
````

2022-12-22 11:58 UTC, closed without merging